In [1]:
import pandas as pd

df = pd.read_csv("MICRODADOS_ENEM_2019.csv",sep=";",encoding = "ISO-8859-1",decimal=",")

df.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,3552205,Sorocaba,35,SP,36.0,M,1,3,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,2910800,Feira de Santana,29,BA,23.0,M,1,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,2304400,Fortaleza,23,CE,39.0,F,1,3,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,1721000,Palmas,17,TO,25.0,F,1,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,3118601,Contagem,31,MG,22.0,F,1,1,...,B,A,A,B,A,A,C,B,B,B

In [2]:
import dask
import dask.dataframe as dd

dfdask = dd.read_csv("MICRODADOS_ENEM_2019.csv",sep=";",encoding = "ISO-8859-1",dtype={'NU_IDADE': 'float64'})

dfdask.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,3552205,Sorocaba,35,SP,36.0,M,1,3,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,2910800,Feira de Santana,29,BA,23.0,M,1,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,2304400,Fortaleza,23,CE,39.0,F,1,3,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,1721000,Palmas,17,TO,25.0,F,1,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,3118601,Contagem,31,MG,22.0,F,1,1,...,B,A,A,B,A,A,C,B,B,B

In [1]:
descriDask = dfdask.describe(include='all')

NameError: name 'dfdask' is not defined

In [4]:
#dfBig.info


meuArquivo = open('file.txt', 'w')
meuArquivo.write(str(descriDask))
meuArquivo.close()

In [5]:
df = df.dropna(subset=["NU_NOTA_REDACAO", "NU_NOTA_CN","NU_NOTA_CH","NU_NOTA_LC","NU_NOTA_MT"])

columns = df.columns

redacao = df["NU_NOTA_REDACAO"]	

print(redacao.size)

3702007

In [6]:
r = redacao[:30]

for i in r:
    print(i)

460.0
860.0
800.0
600.0
400.0
500.0
300.0
240.0
520.0
560.0
660.0
380.0
500.0
600.0
900.0
520.0
580.0
660.0
540.0
620.0
660.0
580.0
300.0
640.0
640.0
0.0
860.0
460.0
620.0
480.0

In [8]:
values = df.value_counts()

print(values)

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA  NO_MUNICIPIO_RESIDENCIA  CO_UF_RESIDENCIA  SG_UF_RESIDENCIA  NU_IDADE  TP_SEXO  TP_ESTADO_CIVIL  TP_COR_RACA  TP_NACIONALIDADE  CO_MUNICIPIO_NASCIMENTO  NO_MUNICIPIO_NASCIMENTO  CO_UF_NASCIMENTO  SG_UF_NASCIMENTO  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  CO_ESCOLA   CO_MUNICIPIO_ESC  NO_MUNICIPIO_ESC  CO_UF_ESC  SG_UF_ESC  TP_DEPENDENCIA_ADM_ESC  TP_LOCALIZACAO_ESC  TP_SIT_FUNC_ESC  IN_BAIXA_VISAO  IN_CEGUEIRA  IN_SURDEZ  IN_DEFICIENCIA_AUDITIVA  IN_SURDO_CEGUEIRA  IN_DEFICIENCIA_FISICA  IN_DEFICIENCIA_MENTAL  IN_DEFICIT_ATENCAO  IN_DISLEXIA  IN_DISCALCULIA  IN_AUTISMO  IN_VISAO_MONOCULAR  IN_OUTRA_DEF  IN_GESTANTE  IN_LACTANTE  IN_IDOSO  IN_ESTUDA_CLASSE_HOSPITALAR  IN_SEM_RECURSO  IN_BRAILLE  IN_AMPLIADA_24  IN_AMPLIADA_18  IN_LEDOR  IN_ACESSO  IN_TRANSCRICAO  IN_LIBRAS  IN_TEMPO_ADICIONAL  IN_LEITURA_LABIAL  IN_MESA_CADEIRA_RODAS  IN_MESA_CADEIRA_SEPARADA  IN_APOIO_PERNA  IN_GUIA_INTERPRETE  IN_COMPUTADOR  IN_CADEIRA_ESPECIAL  IN_CADEIRA_CANHOTO  IN_CADEIRA_ACOLCHOADA  IN_PROVA_DEITADO  IN_MOBILIARIO_OBESO  IN_LAMINA_OVERLAY  IN_PROTETOR_AURICULAR  IN_MEDIDOR_GLICOSE  IN_MAQUINA_BRAILE  IN_SOROBAN  IN_MARCA_PASSO  IN_SONDA  IN_MEDICAMENTOS  IN_SALA_INDIVIDUAL  IN_SALA_ESPECIAL  IN_SALA_ACOMPANHANTE  IN_MOBILIARIO_ESPECIFICO  IN_MATERIAL_ESPECIFICO  IN_NOME_SOCIAL  CO_MUNICIPIO_PROVA  NO_MUNICIPIO_PROVA      CO_UF_PROVA  SG_UF_PROVA  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  TP_PRESENCA_MT  CO_PROVA_CN  CO_PROVA_CH  CO_PROVA_LC  CO_PROVA_MT  NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT  TX_RESPOSTAS_CN                                TX_RESPOSTAS_CH                                TX_RESPOSTAS_LC                                     TX_RESPOSTAS_MT                                TP_LINGUA  TX_GABARITO_CN                                 TX_GABARITO_CH                                 TX_GABARITO_LC                                      TX_GABARITO_MT                                 TP_STATUS_REDACAO  NU_NOTA_COMP1  NU_NOTA_COMP2  NU_NOTA_COMP3  NU_NOTA_COMP4  NU_NOTA_COMP5  NU_NOTA_REDACAO  Q001  Q002  Q003  Q004  Q005  Q006  Q007  Q008  Q009  Q010  Q011  Q012  Q013  Q014  Q015  Q016  Q017  Q018  Q019  Q020  Q021  Q022  Q023  Q024  Q025
190001004629  2019    1505502                  Paragominas              15                PA                18.0      F        1                1            1                 1505502.0                Paragominas              15.0              PA                2                0                3          1.0        0             15230023.0  1505502.0         Paragominas       15.0       PA         4.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               1505502             Paragominas             15           PA           1               1               1               1               505.0        510.0        513.0        518.0        574.2       538.7       582.6       571.5       AABDAECAECECCBCBDECCCBCDBBABABADACBDEADEDABEE  ABACCEABCDADABACBBCEACDACDBBEEBACABBAEACAADCE  ADBBC99999EDBCBBAACECCDCDAACECAABCDCCEDEBAECEAAACC  DECCABCBCDBBBEAECBDBBCDDAADEBCBCACBBEDADDEEAC  0          DADCCEBBCCACBEEBEEBACBCDDDDADBCBBCEAEADEADAAE  EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB  ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBDBBCC  DBEBACABCDBABECEEEDCBDCCEDCDABEDAADDDECACAECB  1.0                140.0          120.0          120.0          140.0          120.0          640.0            H     E     A     D     3     C     D     E     E     C     A     B     C     B     A     B     A     A     D     B     B     D     A     C     B       1
190003750081  2019    2700300                  Arapiraca                27                AL                19.0      M        1                3            1                 2700300.0                Arapiraca                27.0              AL                2                0                2          1.0        0             27016528.0  2700300.0         Arapiraca         27.0       AL         2.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               2700300             Arapiraca               27           AL           1               1               1               1               505.0        508.0        512.0        518.0        425.9       352.2       366.6       429.8       DABCBDACBBCCEABDEBDCBBEEDAEBAEBAECEBDACDCEAAE  EADAECABBEACCEACEDCCDABACDADBADCEADBCAECBDACE  CBBBE99999DCEADAABABBBECDEEEAABDBCBEDBDCBCCEDBEEBC  EDCCAEBBADABDDCAEBBAECCBAECDECBADBEDCEBCCDAEA  0          DADCCEBBCCACBEEBEEBACBCDDDDADBCBBCEAEADEADAAE  CBABADBBCEEEBCBADCBEEDBBEADBBACDBBACCCCADACAC  BBEDABDACACBABAECBBCCADCEBDBBCDDEEAAADDBECDECAAECD  DBEBACABCDBABECEEEDCBDCCEDCDABEDAADDDECACAECB  1.0                100.0          120.0          120.0          120.0          100.0          560.0            C     D     A     B     4     B     A     B     B     A     A     B     A     A     A     A     A     A     B     A     A     B     A     A     A       1
190003750087  2019    2704302                  Maceió                   27                AL                16.0      F        1                2            1                 2704302.0                Maceió                   27.0              AL                2                0                2          1.0        0             27041042.0  2708907.0         Satuba            27.0       AL         1.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               2704302             Maceió                  27           AL           1               1               1               1               506.0        509.0        514.0        517.0        526.4       526.4       545.5       565.9       EEDDBBBAEBEDACACEBEDEABDBDAECBDBBCBDABECDDCDB  AACCCCECABCDADBEBBEEBBEEADBABACAACCABBDBEAAAE  CBBAB99999BBCEEDEAEBEACDCADDCECADBBBBCDACBCECCDDEC  EABADCDCCBEDDDACBACDABBAEDEBCBCADDBBCEEAEDBEC  0          DEADBAAAEBEECEBCBCBCBDADAEABCEDDDDADCBEECACBC  ACACEEBCCBABADBBBACDBBACCCCADCEBADCBEEDBBEADB  EBBADCABDABACBCEBDEEAAADDBECDECDDBADBCDAAECBCCAECB  AADDDBEEEBEDDBEBACABCDBABECECACAECDCBDCCEDCDA  1.0                140.0          120.0          140.0          140.0          140.0          680.0            E     F     D     D     4     H     A     C     D     C     A     B     B     B     A     B     A     A     B     A     A     E     A     B     B       1
190003750093  2019    2706406                  Pão de Açúcar            27                AL                17.0      M        1                3            1                 2706406.0                Pão de Açúcar            27.0              AL                2                0                3          1.0        0             27005933.0  2706406.0         Pão de Açúcar     27.0       AL         4.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               2705705             Olho d'Água das Flores  27           AL           1               1               1               1               504.0        509.0        514.0        516.0        537.2       544.6       530.4       687         AECCBECBDBADDDDCBEAEBCCEDBABBBCBCCDEBDADEBBCD  AEBCEECDABCABDEADEBCAEECCCBAECEABDEBEADBDAEDE  ACBAD99999EDCBCDAADBAAEDEABEDECBAAEAEAEDEECBACBECC  EBDEDBAADECBBEABCDEACEAACDEAECBAABEDBEBCCEEAC  0          BEEAAEBEEBADEADDADAEABCEDDDBCBCBCCACBCDADCCEB  ACACEEBCCBABADBBBACDBBACCCCADCEBADCBEEDBBEADB  EBBADCABDABACBCEBDEEAAADDBECDECDDBADBCDAAECBCCAECB  BEDEEEAADBEBACABCDBABECECACADCBDCCEDCDABECDDD  1.0                120.0          120.0          120.0          120.0          140.0          620.0            E     F     C     D     7     I     A     B     C     A     B     B     A     A     A     A     A     A     B     B     A     C     A     B     B       1
190003750114  2019    2700409                  Atalaia                  27                AL                18.0      F        1                3            1                 2700409.0                Atalaia                  27.0              AL                2                0                3          1.0        0             27352013.0  2700409.0         Atalaia           27.0       AL         4.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               2700409             Atalaia                 27           AL           1               1               1               1               503.0        510.0        513.0        515.0        483.3       431.7       437.8       390.2       AECADBBEACEDCBAABCECBBC.BABDEBBDEBBCEACBBDBBA  ACAACABEACEACEADCBCAECADCECDCBCABDECAABCEAACA  99999AABCDDBDABEAEBCCADBACAEBCEBABBEACBAEBBEDAEABA  DABCCEDCCBDBCABCBBEBACABECEACBEBBAEAEBDCBACBC  1          AAECACDEADCBCDDDBCBDADAEABCEBABEEBCBEECEBDADC  EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB  ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBDBBCC  EEEADBEBACABCDBABECECACDCBDCCEDCDABEDECDDDBAA  1.0                120.0          160.0          120.0          120.0          80.0           600.0            A     A     C     B     4     B     A     D     D     A     A     B     B     B     A     B     A     A     D     B     B     D     A     A     B       1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ..
190002352273  2019    3547809                  Santo André              35                SP                17.0      M        1                3            1                 3547809.0                Santo André              35.0              SP                2                0                2          1.0        0             35029178.0  3547809.0         Santo André       35.0       SP         2.0                     1.0                 1.0              0               0            0          0                        0                  0                      0                      0                   0            0               0           0                   0             0            0            0         0                            0               0           0               0               0         0          0               0          0                   0                  0                      0                         0               0                   0              0                    0                   0                      0                 0                    0                  0                      0                   0                  0           0               0         0                0                   0                 0                     0                         0                       0               3547809             Santo André             35           SP           1               1               1               1               505.0        510.0        513.0        518.0        517.9       522.9       560.8       669.8       BBECADBBCDECCEEAEBDDDACDBCADABEBBBDADAAEEAACE  EECDCEDCCCBCDBABEEAACCBBCCBAEBADEACCDBCDABDAB  ABBBE99999BDECBABACECEDEEDAADAADDCDCEEDEBEEECECECA  DCABACCBBDEDEEAEBBDCBDEAEBDEBAAAAAAABDDAEADEC  0          DADCCEBBCCACBEEBEEBACBCDDDDADBCBBCEAEADEADAAE  EEBCEEDBADBBCBABCCADCEBACDBBACCACACBEADBBADCB  ADBBEDCABAABBCBCDAAECDDDBAAAECADECDCEBDEEAECBDBBCC  DBEBACABCDBABECEEEDCBDCCEDCDABEDAADDDECACAECB  1.0                140.0          120.0          100.0          100.0          80.0           540.0            E     G     B     B     4     D     B     B     C     C     B     B     B     B     A     A     A     B     B     B     A     C     B     B     B       1

In [ ]:
meuArquivo = open('file.txt', 'w')
meuArquivo.write(str(values))
meuArquivo.close()